spring.application.name=documind

server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

logging.level.root=INFO
logging.level.com.documind=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n

# PostgreSQL (RENDER)
spring.datasource.url=jdbc:postgresql://dpg-d6vtfkp5pdvs738shbe0-a.oregon-postgres.render.com:5432/documind_db_najy
spring.datasource.username=documind_db_najy_user
spring.datasource.password=QZPeka8kVzAIiAbcZOUTt87DCP9M4gHq

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect